name: tap-automation-v1
run-name: ${{ github.actor }}
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *" 
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi, thank you for creating your first issue, since this project in solely maintained by me, it may take some time'
        pr-message: 'thanks for your PR, will look into it'